### ISSUE TITLE
Do I need any Swift code if I want to rely on the iOS default share sheet?

### ISSUE THREAD

**Issue by alediaferia** [BreckoEC/share-extension-expo-plugin#2]
Hey,
first of all thank you for sharing this, it's exactly what I was looking for for my project.

I have a very simple share use case: allow to share URLs to my app. Do I need to implement any Swift code even if I just want to rely on iOS provided share sheet?

Any pointer would be appreciated.
Thanks again for your work!

**Comment by yogit-nickelfox** [comment]
sed life!

**Comment by BreckoEC** [comment]
Hello, sorry for the very late reply ! I did not received the notification.
You need to write the share sheet in swift yes, you can find a simple example in my github (the link is https://github.com/BreckoEC/share-extension-expo-example)
